### ISSUE TITLE
Error if no local installation of py.test is available, even if only remote test is to be performed

### ISSUE THREAD

**Issue by mtausig** [mschuchard/packer-plugin-testinfra#3]
I am trying to run a testinfra test of a VM only remotely (i.e. inside the VM) using the SSH connector. I have manually configured this in the packerfile by setting the `local` parameter to `false`:

```
  provisioner "testinfra" {
    processes = 1
    sudo = false
    local = false
    pytest_path = "/usr/bin/py.test"
    test_files = ["/tmp/test.py"]
  }
```
 This results in the immediate (i.e. before the VM is created) error message

```
Error: Failed preparing provisioner-block "testinfra" ""

  on test.pkr.hcl line 250:
  (source code not available)

CreateFile /usr/bin/py.test: The system cannot find the path specified.
```

If I ommit the `pytest_path` parameter I get a slightly different error:

   exec: "py.test": executable file not found in %PATH%

(I am building a Linux VM on a Windows host, hence the `%PATH%` part).

I do not have `py.test` installed on the buildhost and am not able to do so. It also shouldn't be necessary, as I only want to run the tests inside the VM.

**Comment by mschuchard** [comment]
If you are executing the tests locally on the instance being built then the `local` parameter should be assigned a value of `true`. The default `false` is if the tests execute remotely from the machine building the image.

**Comment by mschuchard** [comment]
Question answered and no further replies; closing.
