### ISSUE TITLE
Possible port problem forwarding to test infra

### ISSUE THREAD

**Issue by duartecoelhomovai** [mschuchard/packer-plugin-testinfra#4]
Hello, 
Don't know if im doing something wrong using your plugin, but this happened:

![image](https://github.com/mschuchard/packer-plugin-testinfra/assets/84720623/dec97986-7402-4535-9bcf-a09ff818b5e7)

I aligned all your requirements but still was not able to achieve success.
Packer version:  1.10.1
pytest: 7.2.1
pytest-testinfra: 10.1.0

![image](https://github.com/mschuchard/packer-plugin-testinfra/assets/84720623/1fc37667-6e36-44de-a396-344b50eb70ed)

So it seems like the plugin is passing more than just the port. Seems to be passing '2619 --ssh-extra-args="-o StrictHostKeyChecking=no"' as the port leading to that error, instead of just '2619'.

**Comment by mschuchard** [comment]
I notice from the logs that this is an older version of the plugin. I also have not yet acceptance tested with Packer 1.10 or Testinfra 10. Regardless it appears this is some kind of type interfacing issue between Go and Python that would probably be independent of anything's version, and that I need to investigate further why Testinfra/Python is not parsing the command correctly as passed from Go.

**Comment by duartecoelhomovai** [comment]
> I notice from the logs that this is an older version of the plugin. I also have not yet acceptance tested with Packer 1.10 or Testinfra 10. Regardless it appears this is some kind of type interfacing issue between Go and Python that would probably be independent of anything's version, and that I need to investigate further why Testinfra/Python is not parsing the command correctly as passed from Go. There is also the possibility that a new version of Testinfra is parsing SSH arguments with different usage, but basically there are enough different possibilities that this will take time to determine root cause.

If you want me to test with a specific set of requirements that you are confortable with let me know

**Comment by duartecoelhomovai** [comment]
`provisioner "shell-local" {
    inline = [
      "python3 -m pytest -v ${var.pytest_args} --hosts=${build.User}:${build.Password}@${build.Host}:${build.Port} --ssh-extra-args='-o StrictHostKeyChecking=no'"
    ]
  }`

With this it works fine so i would say its most likely a go parsing gone wrong

**Comment by mschuchard** [comment]
Partial fix in e95c035. Communicator issue now fixed as Testinfra+Paramiko does not allow configuration.
Python parsing issue still persists. Explicit string cast causes Pytest to not interpret connection backend, and implicit string cast causes Pytest to not interpret ssh arguments.
